title: "Suvidha Deshpande"
email: suvidhav@buffalo.edu
description: >-
  MS CS @ SUNY Buffalo | AI + Full Stack Developer | Ex-Deloitte, Zycus

baseurl: "" # leave this blank for user.github.io
url: "https://suvidhav.github.io"

linkedin_username: suvidha-deshpande

theme: jekyll-theme-minimal

markdown: kramdown

plugins:
  - jekyll-feed
